import Navbar from '@/components/Navbar';
import Head from 'next/head';
import React from 'react';

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>Auth Example</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='h-screen'>
        <Navbar />
        {children}
      </main>
    </>
  );
};

export default RootLayout;
